name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mosesonwuzua/mostechimages:${{ env.IMAGE_TAG }}

      - name: Tag the Docker image with `latest`
        run: docker tag mosesonwuzua/mostechimages:${{ env.IMAGE_TAG }} mosesonwuzua/mostechimages:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push mosesonwuzua/mostechimages:${{ env.IMAGE_TAG }}
          docker push mosesonwuzua/mostechimages:latest
